server.servlet.context-path=/hp

#MS Access
spring.datasource.driver-class-name=net.ucanaccess.jdbc.UcanaccessDriver
spring.datasource.url=jdbc:ucanaccess://C:/Color World/hp.accdb;openExclusive=false;ignoreCase=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none

account.details=Acc.No : 50200023395572, IFSC : HDFC0000665, HDFC BANK.
tax.invoice.directory=C:\\HP
account.registry.directory=${tax.invoice.directory}\\Account Register

#Company Details
company.name=H.P. TRADING CO.
company.description=205-206/B Bldg no 4, Gautam Nagar, Jay Ambe Mandir Road, Near Holy Cross School,
company.address=Bhayander(W), Thane.
company.contact=Mob: 9820106499. GST No. 27AAACJ6929L1Z4

sales.header=BillNum,BillDate,CompanyName,CompanyGST,TaxableAmount,CGST,SGST,TotalAmount, \
ChequeDate, ChequeNum,ChequeAmount,BankName,Text,BillType

overflowLimit = 16