server.servlet.context-path=/hb

#MS Access
spring.datasource.driver-class-name=net.ucanaccess.jdbc.UcanaccessDriver
spring.datasource.url=jdbc:ucanaccess://C:/Color World/hb.accdb;openExclusive=false;ignoreCase=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=none

account.details=Acc.No : 50200023395572, IFSC : HDFC0000665, HDFC BANK.
tax.invoice.directory=C:\\Tax Invoice
account.registry.directory=C:\\Color World\\Account Register
units=Kg,gm,ml,L,Nos

#Company Details
company.name=HB TRADING CO PVT LTD
company.description=Vimal Dairy Road, Plot no 146-E, Charkop Ind Estate
company.address=Sector no 2, Charkop, Bhayander(E), - 401 107.
company.contact=Mob: 9820106499. GST No. 27AAACJ6929L1Z4

sales.header=BillNum,BillDate,CompanyName,CompanyGST,TaxableAmount,CGST,SGST,TotalAmount, \
ChequeDate, ChequeNum,ChequeAmount,BankName,Text,BillType