server.servlet.context-path=/mrajupaint

#MS Access
spring.profiles.active=dev
spring.datasource.driver-class-name=net.ucanaccess.jdbc.UcanaccessDriver
spring.datasource.url=jdbc:ucanaccess://C:/Color World/jinal.accdb;openExclusive=false;ignoreCase=true
spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.SQLServerDialect

account.details=Acc.No : 50200023395572, IFSC : HDFC0000358, HDFC BANK.
tax.invoice.directory=C:\\Tax Invoice
account.registry.directory=C:\\Color World\\Account Register
units=Kg,gm,ml,L,Nos

#Company Details 
company.name=JINAL TRADING CO PVT LTD
company.description=49 CP Tank Road, Plot no 146-E, Charkop Ind Estate
company.address=Sector no 2, Charkop, Kandivali(W), Mumbai - 400 007.
company.contact=Mob: 9820106499. GST No. 27AAACJ6929L1Z4

sales.header=BillNum,BillDate,CompanyName,CompanyGST,TaxableAmount,CGST,SGST,TotalAmount, \
ChequeDate, ChequeNum,ChequeAmount,BankName,Text,BillType